### PR TITLE
Pulling vendor dependencies into this repo. Adding development enviro…

### PR DESCRIPTION
**Pull request by nielsole**
…nment with echo server

### CODE REVIEW

**Comment by nielsole** [comment]
@hanikesn Should I pull the files into the repo then, or pull them during building?
The idea of this pull request was to reduce the dependency on the hosting providers especially if they were to suddenly serve malware since we do not check file integrity.

**Comment by nielsole** [comment]
Ah I just saw that it even is in the repo. Why would we not have these files in the build environment as you said?

**Comment by hanikesn** [comment]
@nielsole The idea is to have the Dockerfile be completely independent of vendor/ just like it was before.

**Comment by hanikesn** [comment]
There's some binary files left in vendor/ also I don't think we need version.sh anymore.

**Pull request merged**
